name: Growbie
main: com.afforess.growbie.Growbie
version: 2.0
authors: [Afforess, Cyklo, UnixSystem]
description: A Simple Mod that allows bonemeal to grow grass on dirt, spread pumpkins, and spread flowers